# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Berat Gümüş
description: > # this means to ignore newlines until "baseurl:"
  <p>
  Junior computer engineering student at Ege University. <br>
  I love; coding, solving algorithms, fitness, healthy foods.<br>
  I like; basketball, thinking, travelling.<br><br>
  </p>
  <h2>Mail me via code below</h2>
  <div><kbd>
  var username = "beratgumus9";<br>
  var hostname = "gmail.com";<br>
  var myEmail = username + "@" + hostname;<br>
  mailTo(myEmail);
  </kbd><div>


baseurl: "" # the subpath of your site, e.g. /blog
url: "https://beratgumus.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'Berat Gümüş'
  last_name: 'Gümüş'
  cv: '//beratgumus.github.io'
  avatar: '/images/bg.ico'
  github_username:  beratgumus  
  email: 
  vk_id: 
  telegram_name: 
  logo: '/images/bg.ico'

# Build settings
markdown: kramdown

permalink: /:title


